version: '3'
services:
  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    networks:
      - rag-network

  rag-app:
    build:
      context: .
    ports:
      - "8501:8501"
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      - chroma
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
